-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.options")
require("config.editor")
require("config.lazy")
require("config.keymaps")
require("config.autocmds")
require("config.java")
require("config.maven")
require("config.dap.java")
require("config.dap.hydra")
require("config.dap.python")
